version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: habit-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: habit-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/habitdb
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo

volumes:
  mongo_data:
